import {
  Atom, Mountain, Bitcoin, Dna, Ticket, Droplets, Wrench, Brain,
  Cpu, CircuitBoard, Landmark, CreditCard, Building2, Truck,
  Shield, ShieldCheck, Rocket, Gamepad2, Zap, Globe, BarChart3, DollarSign,
  TrendingUp, Briefcase, PiggyBank, Sparkles, Package, Gem,
  Leaf, Heart, Car, Factory, Satellite, ShoppingBag,
  Settings, GraduationCap,
  type LucideIcon,
} from 'lucide-react';

export const iconMap: Record<string, LucideIcon> = {
  atom: Atom,
  mountain: Mountain,
  bitcoin: Bitcoin,
  dna: Dna,
  ticket: Ticket,
  droplets: Droplets,
  wrench: Wrench,
  brain: Brain,
  cpu: Cpu,
  'circuit-board': CircuitBoard,
  landmark: Landmark,
  'credit-card': CreditCard,
  building: Building2,
  truck: Truck,
  shield: Shield,
  'shield-check': ShieldCheck,
  rocket: Rocket,
  gamepad: Gamepad2,
  zap: Zap,
  globe: Globe,
  'bar-chart': BarChart3,
  dollar: DollarSign,
  trending: TrendingUp,
  briefcase: Briefcase,
  piggy: PiggyBank,
  sparkles: Sparkles,
  package: Package,
  gem: Gem,
  leaf: Leaf,
  heart: Heart,
  car: Car,
  factory: Factory,
  satellite: Satellite,
  'shopping-bag': ShoppingBag,
  cog: Settings,
  'graduation-cap': GraduationCap,
};

export const defaultIcon: LucideIcon = Globe;
